apiVersion: v1
  kind: Secret
  metadata:
    name: aws-secret
  type: Opaque
  data:
    AWS_BUCKET: udagram-diallo-s3-dev
    AWS_PROFILE: default
    AWS_REGION: us-west-2
    JWT_SECRET: helloworld
    POSTGRESS_DB: udagramdiallodev
    POSTGRESS_HOST: udagramdiallodev.cgsh6ixl53fs.us-east-2.rds.amazonaws.com