version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: 224apps/reverseproxy 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: 224apps/udacity-c3-restapi-user 
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: 224apps/udacity-c3-restapi-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: 224apps/udacity-c3-frontend 